apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-monitor-sa
  namespace: pod-monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-monitor-role
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes", "persistentvolumeclaims",
                "services", "endpoints", "configmaps", "secrets", "serviceaccounts",
                "resourcequotas", "limitranges"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list"]
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-monitor-admin-role
  namespace: pod-monitor
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-monitor-admin-binding
  namespace: pod-monitor
subjects:
  - kind: ServiceAccount
    name: pod-monitor-sa
    namespace: pod-monitor
roleRef:
  kind: Role
  name: pod-monitor-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-monitor-binding
subjects:
  - kind: ServiceAccount
    name: pod-monitor-sa
    namespace: pod-monitor
roleRef:
  kind: ClusterRole
  name: pod-monitor-role
  apiGroup: rbac.authorization.k8s.io
