{{- if and .Values.ingress.enabled (not .Values.openshift.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pod-monitor-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pod-monitor.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
{{- end }}
